// Archivo generado automáticamente. Edita solo si sabes lo que haces.
const media = [
    { name: "Propose", artist: "9Lana", file: "music/9Lana - propose.mp4", type: "video" },
    { name: "Thunderstruck", artist: "AC_DC", file: "music/AC_DC - Thunderstruck.mp4", type: "video" },
    { name: "Where's My Head At", artist: "Basement Jaxx & 100 gecs", file: "music/Basement Jaxx & 100 gecs - where's my head at _.mp4", type: "video" },
    { name: "1-800", artist: "bbno$ & Ironmouse", file: "music/bbno$ & Ironmouse - 1-800.mp4", type: "video" },
    { name: "Cry", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - Cry.mp4", type: "video" },
    { name: "Don't Let Me Go", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - Don't Let Me Go.mp4", type: "video" },
    { name: "Falling In Love", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - Falling In Love.mp4", type: "video" },
    { name: "Heavenly", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - Heavenly.mp4", type: "video" },
    { name: "Hentai", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - Hentai.mp4", type: "video" },
    { name: "Kiss It Off Me", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - Kiss It Off Me.mp4", type: "video" },
    { name: "Pure", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - Pure.mp4", type: "video" },
    { name: "Touch", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - Touch.mp4", type: "video" },
    { name: "You're the Only Good Thing In My Life", artist: "Cigarettes After Sex", file: "music/Cigarettes After Sex - You're the Only Good Thing In My Life.mp4", type: "video" },
    { name: "Daylight", artist: "David Kushner", file: "music/David Kushner - Daylight.mp4", type: "video" },
    { name: "Woops", artist: "DJ Bountyhunter", file: "music/DJ Bountyhunter - Woops.mp4", type: "video" },
    { name: "Bodies", artist: "Drowning Pool", file: "music/Drowning Pool - Bodies.mp4", type: "video" },
    { name: "Survivor / I Will Survive", artist: "Glee Cast", file: "music/Glee Cast - Survivor _ I Will Survive (Cover of Destiny's Child and Gloria Gaynor).mp4", type: "video" },
    { name: "19-2000", artist: "Gorillaz", file: "music/Gorillaz - 19-2000.mp4", type: "video" },
    { name: "Take Me to the Beach", artist: "Imagine Dragons", file: "music/Imagine Dragons - Take Me to the Beach.mp4", type: "video" },
    { name: "Meant to be Yours", artist: "Jamie Muscato & Original West End Cast of Heathers", file: "music/Jamie Muscato & Original West End Cast of Heathers - Meant to be Yours.mp4", type: "video" },
    { name: "3D - Justin Timberlake Remix", artist: "Jung Kook & Justin Timberlake", file: "music/Jung Kook & Justin Timberlake - 3D - Justin Timberlake Remix.mp4", type: "video" },
    { name: "Monster", artist: "Kanye West", file: "music/Kanye West - Monster.mp4", type: "video" },
    { name: "Freak On a Leash", artist: "Korn", file: "music/Korn - Freak On a Leash.mp4", type: "video" },
    { name: "Rollin' (Air Raid Vehicle)", artist: "Limp Bizkit", file: "music/Limp Bizkit - Rollin' (Air Raid Vehicle).mp4", type: "video" },
    { name: "Given Up", artist: "Linkin Park", file: "music/Linkin Park - Given Up.mp4", type: "video" },
    { name: "In the End", artist: "Linkin Park", file: "music/Linkin Park - In the End.mp4", type: "video" },
    { name: "GOSSIP", artist: "Måneskin", file: "music/Måneskin - GOSSIP.mp4", type: "video" },
    { name: "Enter Sandman", artist: "Metallica", file: "music/Metallica - Enter Sandman.mp4", type: "video" },
    { name: "Master Of Puppets", artist: "Metallica", file: "music/Metallica - Master Of Puppets.mp4", type: "video" },
    { name: "Inferno", artist: "Mrs. GREEN APPLE", file: "music/Mrs. GREEN APPLE - Inferno.mp4", type: "video" },
    { name: "No Surprises", artist: "Radiohead", file: "music/Radiohead - No Surprises.mp4", type: "video" },
    { name: "Amerika", artist: "Rammstein", file: "music/Rammstein - Amerika.mp4", type: "video" },
    { name: "Du hast", artist: "Rammstein", file: "music/Rammstein - Du hast.mp4", type: "video" },
    { name: "Te quiero puta!", artist: "Rammstein", file: "music/Rammstein - Te quiero puta!.mp4", type: "video" },
    { name: "Nothing's New", artist: "Rio Romeo", file: "music/Rio Romeo - Nothing's New.mp4", type: "video" },
    { name: "Dragula", artist: "Rob Zombie", file: "music/Rob Zombie - Dragula.mp4", type: "video" },
    { name: "Vicinity Of Obscenity", artist: "System Of A Down", file: "music/System Of A Down - Vicinity Of Obscenity.mp4", type: "video" },
    { name: "You Don't Know Me", artist: "Oakland", file: "music/Oakland - You Don't Know Me.mp4", type: "video" },
];
